// <auto-generated />
using System;
using Blazor.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blazor.Db.Migrations
{
    [DbContext(typeof(BlazorContext))]
    [Migration("20220909085203_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blazor.Db.Entities.Books.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PagesCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Джоан Роулинг",
                            PagesCount = 500,
                            PublishDate = new DateTime(1988, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Гарри Поттер и Орден Феникса"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Джоан Роулинг",
                            PagesCount = 600,
                            PublishDate = new DateTime(1990, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Гарри Поттер и Кубок Огня"
                        });
                });

            modelBuilder.Entity("Blazor.Db.Entities.Books.BookPrices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("BookPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Price = 300m
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            Price = 350m
                        });
                });

            modelBuilder.Entity("Blazor.Db.Entities.Books.BookPrices", b =>
                {
                    b.HasOne("Blazor.Db.Entities.Books.Book", "Book")
                        .WithOne("BookPrices")
                        .HasForeignKey("Blazor.Db.Entities.Books.BookPrices", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Blazor.Db.Entities.Books.Book", b =>
                {
                    b.Navigation("BookPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
